-- ============================================================================
-- EmergentOS Phase 1 - Calendar Insights Enhancement Migration
-- Version: 1.0
-- Date: January 26, 2026
-- 
-- Adds health_score and verdict columns to calendar_insights table
-- for enhanced structured output from calendar analysis.
-- ============================================================================

-- Add health_score column (0-100 integer score)
ALTER TABLE calendar_insights
ADD COLUMN IF NOT EXISTS health_score INTEGER DEFAULT 50;

-- Add verdict column (OPTIMAL, GOOD, CONCERNING, CRITICAL)
ALTER TABLE calendar_insights
ADD COLUMN IF NOT EXISTS verdict TEXT DEFAULT 'MODERATE';

-- Add constraint for verdict values
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'calendar_insights_verdict_check'
  ) THEN
    ALTER TABLE calendar_insights
    ADD CONSTRAINT calendar_insights_verdict_check
    CHECK (verdict IN ('OPTIMAL', 'GOOD', 'CONCERNING', 'CRITICAL', 'MODERATE'));
  END IF;
END $$;

-- Add constraint for health_score range
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'calendar_insights_health_score_check'
  ) THEN
    ALTER TABLE calendar_insights
    ADD CONSTRAINT calendar_insights_health_score_check
    CHECK (health_score >= 0 AND health_score <= 100);
  END IF;
END $$;

-- Add index for health score filtering
CREATE INDEX IF NOT EXISTS idx_calendar_insights_health_score 
ON calendar_insights (user_id, health_score);

-- Comment on new columns
COMMENT ON COLUMN calendar_insights.health_score IS 'Overall calendar health score from 0-100, generated by AI analysis';
COMMENT ON COLUMN calendar_insights.verdict IS 'Overall calendar verdict: OPTIMAL (80+), GOOD (60-79), CONCERNING (40-59), CRITICAL (<40)';
